// Copyright 2019 RADAR, Inc. - All Rights Reserved
// Proprietary and confidential

pipeline {
    agent {
        docker {
            registryUrl 'https://docker.inradar.net'
            registryCredentialsId 'radar-docker-registry'
            image 'docker.inradar.net/ubuntu-20.04-boost:0.2.4'
            label 'docker'
        }
    }

    environment {
        PREFIX = "${WORKSPACE}/installed"
    }

    stages {
        stage('Boost.Build Setup') {
            steps {
                sh '''
                echo "# DO NOT EDIT - generated by Dockerfile" > tmp-user-config.jam
                echo "using doxygen ;" >> tmp-user-config.jam
                '''
            }
        }
        stage('Documentation') {
            steps {
                sh 'b2 --user-config=tmp-user-config.jam --verbose-test documentation | tee doxygen.log'

                recordIssues(tools: [doxygen(pattern: 'doxygen.log')])

                publishHTML([allowMissing: false,
                             alwaysLinkToLastBuild: true,
                             keepAll: false,
                             reportDir: 'project/bb/libll/html/api',
                             reportFiles: 'index.html',
                             reportName: 'libll API Reference Documentation',
                             reportTitles: ''])

                publishHTML([allowMissing: false,
                             alwaysLinkToLastBuild: true,
                             keepAll: false,
                             reportDir: 'project/bb/libtl/html/api',
                             reportFiles: 'index.html',
                             reportName: 'libtl API Reference Documentation',
                             reportTitles: ''])
            }
        }
        stage('Build') {
            steps {
                sh 'b2 --user-config=tmp-user-config.jam --verbose-test project/bb/example variant=debug,release | tee gcc.log'

                recordIssues(tools: [gcc4(pattern: 'gcc.log')])
            }
        }
        stage('Test') {
            environment {
                BOOST_TEST_LOGGER = 'JUNIT'
            }

            steps {
                sh 'b2 --user-config=tmp-user-config.jam --verbose-test variant=debug,release'

                junit '*.xml'
            }
        }
        stage('Install') {
            steps {
                sh 'b2 --user-config=tmp-user-config.jam --verbose-test variant=release install --prefix=${PREFIX}'
            }
        }
    }
}
